CREATE DATABASE IF NOT EXISTS DATABASEPHP;
USE DATABASEPHP;
CREATE TABLE IF NOT EXISTS USUARIOS (
	ID INT NOT NULL PRIMARY KEY auto_increment,
    NOME VARCHAR(50) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    IMAGEM varchar(50) NOT NULL,
    DATAATUAL DATETIME
);

SELECT * FROM USUARIOS;


